"use client";

import { useMemo, useState } from "react";
import { labourers } from "@/data/supervisor";
import { createSupervisorTask, supervisorStore } from "@/lib/supervisor";
import { ConversationMessage, SupervisorTask } from "@/types/supervisor";

const starter: ConversationMessage[] = [{ id: "welcome", role: "assistant", content: "Tell me what needs to happen on site. I’ll turn it into a task, suggest its L1–L6 placement, and recommend a specific labourer for your approval." }];

export default function ConversePage() {
  const [messages, setMessages] = useState(starter); const [value, setValue] = useState(""); const [draft, setDraft] = useState<SupervisorTask | null>(null); const [sent, setSent] = useState(false);
  const suggestedLabourer = useMemo(() => draft ? labourers.find(labourer => labourer.id === draft.suggestedLabourerId) : null, [draft]);
  const send = () => { if (!value.trim()) return; const next = createSupervisorTask({ description: value.trim(), location: "Location to be confirmed", dueDate: "2026-09-05", priority: "Medium", source: "Converse" }); setMessages(items => [...items, { id: `user-${Date.now()}`, role: "user", content: value.trim() }, { id: `assistant-${Date.now()}`, role: "assistant", content: `I’ve prepared an L${next.classification.level} ${next.classification.discipline.toLowerCase()} task and recommended ${labourers.find(labourer => labourer.id === next.suggestedLabourerId)?.name}. Review the draft on the right before sending it.` }]); setDraft(next); setSent(false); setValue(""); };
  const approve = () => { if (!draft) return; const saved = { ...draft, status: "Assigned" as const, assignedLabourerId: draft.suggestedLabourerId, dispatchStatus: "Sent" as const }; supervisorStore.saveTasks([saved, ...supervisorStore.tasks()]); setDraft(saved); setSent(true); };
  return <div className="space-y-6"><div><h1 className="text-2xl lg:text-3xl font-semibold tracking-tight">Converse to Task</h1><p className="mt-2 text-text-secondary text-base lg:text-lg">Use plain language. The assistant converts your field instruction into an approval-ready task.</p></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
    <section className="card flex flex-col min-h-[610px]"><div className="p-5 border-b"><p className="font-semibold">Supervisor assistant</p><p className="text-sm text-text-secondary mt-1">Prototype mode · recommendations are simulated</p></div><div className="flex-1 p-5 space-y-4 overflow-y-auto">{messages.map(message => <div key={message.id} className={`max-w-[85%] rounded-lg px-4 py-3 text-sm ${message.role === "user" ? "ml-auto bg-primary text-white" : "bg-bg border border-border text-text-primary"}`}>{message.content}</div>)}</div><div className="p-4 border-t"><div className="flex gap-3"><input value={value} onChange={e => setValue(e.target.value)} onKeyDown={e => e.key === "Enter" && send()} placeholder="e.g. Ask the electrical crew to check conduits before the slab pour." className="flex-1 px-3 py-2.5 border border-border rounded-lg bg-surface-elevated text-sm focus:outline-none focus:ring-2 focus:ring-primary" /><button onClick={send} className="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-light">Send</button></div><p className="mt-2 text-xs text-text-muted">Try “make it critical”, “use Electrical Team D”, or “split this into two tasks” after creating a draft.</p></div></section>
    <aside className="card p-5 h-fit"><p className="text-xs uppercase tracking-wide font-medium text-text-secondary">Live task preview</p>{draft ? <div className="mt-3 space-y-5"><div><h2 className="text-lg font-semibold">{draft.title}</h2><p className="mt-2 text-sm text-text-secondary">{draft.description}</p></div><div className="p-4 bg-bg border border-border rounded-lg"><p className="text-xs text-text-secondary">Classification</p><p className="mt-1 font-semibold text-primary">L{draft.classification.level} · {draft.classification.discipline}</p><p className="mt-2 text-sm">{draft.classification.hierarchyLabel}</p><p className="mt-2 text-xs text-text-secondary">{draft.classification.reasoning}</p><p className="mt-3 text-xs font-medium text-status-ontrack">{draft.classification.confidence}% confidence</p></div><div><p className="text-sm font-medium">Recommended labourer</p><p className="mt-1 text-sm text-text-secondary">{suggestedLabourer?.name} · {suggestedLabourer?.trade}</p><p className="mt-1 text-xs text-text-secondary">{suggestedLabourer?.zone} · {suggestedLabourer?.phone}</p><p className="mt-2 text-xs text-text-secondary">{draft.assignmentReason}</p></div>{sent ? <div className="p-3 bg-status-ontrack-bg text-status-ontrack rounded-lg text-sm">Task approved and sent to the mock WhatsApp queue.</div> : <button onClick={approve} className="w-full px-4 py-2.5 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-light">Approve & send to labour</button>}</div> : <div className="py-14 text-center text-text-secondary"><p className="text-lg">Your task draft will appear here.</p><p className="mt-2 text-sm">Describe the work, labourer, deadline, or location in the chat.</p></div>}</aside>
  </div></div>;
}
