"use client";

import { useEffect, useMemo, useState } from "react";
import { supervisorStore } from "@/lib/supervisor";
import { DailyReport, SupervisorTask } from "@/types/supervisor";

export default function ReportsPage() {
  const [reports, setReports] = useState<DailyReport[]>([]); const [tasks, setTasks] = useState<SupervisorTask[]>([]); const [showForm, setShowForm] = useState(false);
  const [workforce, setWorkforce] = useState("53"); const [completedWork, setCompletedWork] = useState(""); const [blockers, setBlockers] = useState(""); const [safetyNote, setSafetyNote] = useState("");
  useEffect(() => {
    const load = window.setTimeout(() => {
      setReports(supervisorStore.reports());
      setTasks(supervisorStore.tasks());
    }, 0);
    return () => window.clearTimeout(load);
  }, []);
  const todayWork = useMemo(() => tasks.filter(t => t.dueDate === "2026-09-04" || t.status === "Completed").map(t => t.title).slice(0, 3), [tasks]);
  const save = (status: DailyReport["status"]) => { const next: DailyReport = { id: `report-${Date.now()}`, date: "2026-09-04", shift: "Day", workforce: Number(workforce) || 0, completedWork: completedWork || todayWork.join("; ") || "No completed work recorded.", blockers: blockers || "No blockers reported.", safetyNote: safetyNote || "Daily safety check completed.", status }; const updated = [next, ...reports]; setReports(updated); supervisorStore.saveReports(updated); setShowForm(false); };
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between sm:items-end gap-4"><div><h1 className="text-2xl lg:text-3xl font-semibold tracking-tight">Daily Reports</h1><p className="mt-2 text-text-secondary text-base lg:text-lg">Capture field progress, labour strength, blockers, and safety observations for the Project Manager.</p></div><button onClick={() => setShowForm(!showForm)} className="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-light">Create today’s report</button></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><p className="text-xs uppercase tracking-wide font-medium text-text-secondary">Today’s tasks</p><p className="mt-1 text-3xl font-semibold">{tasks.filter(t => t.dueDate === "2026-09-04").length}</p></div><div className="card p-5"><p className="text-xs uppercase tracking-wide font-medium text-text-secondary">Completed</p><p className="mt-1 text-3xl font-semibold text-status-ontrack">{tasks.filter(t => t.status === "Completed").length}</p></div><div className="card p-5"><p className="text-xs uppercase tracking-wide font-medium text-text-secondary">Reports submitted</p><p className="mt-1 text-3xl font-semibold text-primary">{reports.filter(r => r.status === "Submitted").length}</p></div></div>
    {showForm && <section className="card p-6"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-semibold">Daily site report</h2><p className="mt-1 text-sm text-text-secondary">04 Sep 2026 · Day shift</p></div><span className="status-badge bg-active-bg text-primary">Draft</span></div><div className="grid gap-4 mt-5 md:grid-cols-2"><label className="text-sm font-medium">Workforce present<input type="number" value={workforce} onChange={e => setWorkforce(e.target.value)} className="block mt-2 w-full px-3 py-2 border border-border rounded-lg bg-surface-elevated" /></label><div className="p-3 bg-bg border border-border rounded-lg"><p className="text-sm font-medium">Task-based suggestions</p><ul className="mt-2 text-sm text-text-secondary space-y-1">{todayWork.length ? todayWork.map(item => <li key={item}>• {item}</li>) : <li>No matching tasks to prefill yet.</li>}</ul></div><label className="text-sm font-medium md:col-span-2">Completed work<textarea value={completedWork} onChange={e => setCompletedWork(e.target.value)} rows={3} placeholder="Describe completed activities and quantities..." className="block mt-2 w-full px-3 py-2 border border-border rounded-lg bg-surface-elevated font-normal" /></label><label className="text-sm font-medium">Blockers or delays<textarea value={blockers} onChange={e => setBlockers(e.target.value)} rows={3} placeholder="Delays, material issues, access constraints..." className="block mt-2 w-full px-3 py-2 border border-border rounded-lg bg-surface-elevated font-normal" /></label><label className="text-sm font-medium">Safety observation<textarea value={safetyNote} onChange={e => setSafetyNote(e.target.value)} rows={3} placeholder="Toolbox talks, incidents, controls..." className="block mt-2 w-full px-3 py-2 border border-border rounded-lg bg-surface-elevated font-normal" /></label></div><div className="flex justify-end gap-3 mt-5"><button onClick={() => save("Draft")} className="px-4 py-2 text-sm font-medium border border-border rounded-lg hover:bg-hover">Save draft</button><button onClick={() => save("Submitted")} className="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-light">Submit to Project Manager</button></div></section>}
    <section className="card overflow-hidden"><div className="p-5 border-b"><h2 className="font-semibold">Report history</h2></div><div className="divide-y divide-border">{reports.length ? reports.map(report => <article key={report.id} className="p-5"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{report.date} · {report.shift} shift</h3><span className={`status-badge ${report.status === "Submitted" ? "bg-status-ontrack-bg text-status-ontrack" : "bg-status-atrisk-bg text-status-atrisk"}`}>{report.status}</span></div><p className="mt-2 text-sm text-text-secondary">{report.completedWork}</p><p className="mt-2 text-xs text-text-secondary">{report.workforce} labourers · Safety: {report.safetyNote}</p></div><button className="text-sm font-medium text-primary h-fit">View report →</button></div></article>) : <p className="p-8 text-center text-text-secondary">No daily reports yet.</p>}</div></section>
  </div>;
}
