"use client";

import { useEffect, useMemo, useState } from "react";
import { labourers } from "@/data/supervisor";
import { createSupervisorTask, supervisorStore } from "@/lib/supervisor";
import { SupervisorTask, TaskPriority } from "@/types/supervisor";

const priorityTone: Record<string, string> = { Low: "bg-status-ontrack-bg text-status-ontrack", Medium: "bg-bg text-text-secondary", High: "bg-status-atrisk-bg text-status-atrisk", Critical: "bg-status-delayed-bg text-status-delayed" };
const statusTone: Record<string, string> = { "Awaiting Approval": "bg-status-atrisk-bg text-status-atrisk", Assigned: "bg-active-bg text-primary", "In Progress": "bg-active-bg text-primary", Completed: "bg-status-ontrack-bg text-status-ontrack", Blocked: "bg-status-delayed-bg text-status-delayed" };

export default function TasksPage() {
  const [tasks, setTasks] = useState<SupervisorTask[]>([]);
  const [text, setText] = useState(""); const [location, setLocation] = useState(""); const [dueDate, setDueDate] = useState("2026-09-05"); const [priority, setPriority] = useState<TaskPriority>("Medium");
  const [filter, setFilter] = useState("All"); const [selectedId, setSelectedId] = useState<string | null>(null);
  useEffect(() => {
    const load = window.setTimeout(() => setTasks(supervisorStore.tasks()), 0);
    return () => window.clearTimeout(load);
  }, []);
  const selected = tasks.find(t => t.id === selectedId) ?? null;
  const visible = useMemo(() => filter === "All" ? tasks : tasks.filter(t => t.status === filter), [tasks, filter]);
  const persist = (next: SupervisorTask[]) => { setTasks(next); supervisorStore.saveTasks(next); };
  const addTask = () => { if (!text.trim()) return; const next = createSupervisorTask({ description: text.trim(), location, dueDate, priority, source: "Manual" }); persist([next, ...tasks]); setSelectedId(next.id); setText(""); setLocation(""); };
  const approve = (task: SupervisorTask, labourerId = task.suggestedLabourerId) => persist(tasks.map(item => item.id === task.id ? { ...item, assignedLabourerId: labourerId, assignedToSelf: false, status: "Assigned", dispatchStatus: "Sent" } : item));
  const assignSelf = (task: SupervisorTask) => persist(tasks.map(item => item.id === task.id ? { ...item, assignedToSelf: true, assignedLabourerId: undefined, status: "In Progress", dispatchStatus: "Not sent" } : item));
  return <div className="space-y-6">
    <div><h1 className="text-2xl lg:text-3xl font-semibold tracking-tight">Todo List</h1><p className="mt-2 text-text-secondary text-base lg:text-lg">Create field work, review the AI proposal, then approve the labour assignment.</p></div>
    <section className="card p-5 lg:p-6"><div className="flex items-center gap-3 mb-4"><span className="w-9 h-9 rounded-lg bg-active-bg text-primary flex items-center justify-center font-semibold">AI</span><div><h2 className="font-semibold">Add a task</h2><p className="text-sm text-text-secondary">The prototype classifies the task and recommends an available crew.</p></div></div><textarea value={text} onChange={e => setText(e.target.value)} rows={3} placeholder="Example: Complete shuttering for beam B12 before tomorrow afternoon." className="w-full px-3 py-2.5 border border-border rounded-lg bg-surface-elevated text-sm placeholder-text-muted focus:outline-none focus:ring-2 focus:ring-primary" />
      <div className="grid gap-3 mt-3 md:grid-cols-4"><input value={location} onChange={e => setLocation(e.target.value)} placeholder="Location / work zone" className="px-3 py-2 border border-border rounded-lg bg-surface-elevated text-sm focus:outline-none focus:ring-2 focus:ring-primary" /><input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} className="px-3 py-2 border border-border rounded-lg bg-surface-elevated text-sm focus:outline-none focus:ring-2 focus:ring-primary" /><select value={priority} onChange={e => setPriority(e.target.value as TaskPriority)} className="px-3 py-2 border border-border rounded-lg bg-surface-elevated text-sm focus:outline-none focus:ring-2 focus:ring-primary"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><button onClick={addTask} className="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-light">Get AI recommendation</button></div>
    </section>
    <div className="flex flex-wrap gap-2">{["All", "Awaiting Approval", "Assigned", "In Progress", "Completed", "Blocked"].map(item => <button key={item} onClick={() => setFilter(item)} className={`px-3 py-1.5 rounded-full text-sm border ${filter === item ? "bg-primary text-white border-primary" : "bg-surface-elevated text-text-secondary border-border hover:bg-hover"}`}>{item}{item === "Awaiting Approval" ? ` (${tasks.filter(t => t.status === item).length})` : ""}</button>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="card overflow-hidden"><div className="divide-y divide-border">{visible.length === 0 ? <p className="p-8 text-center text-text-secondary">No tasks match this filter.</p> : visible.map(task => { const labourer = labourers.find(item => item.id === (task.assignedLabourerId || task.suggestedLabourerId)); return <button key={task.id} onClick={() => setSelectedId(task.id)} className={`w-full text-left p-5 hover:bg-hover transition-colors ${selectedId === task.id ? "bg-active-bg/50 border-l-4 border-primary" : ""}`}><div className="flex gap-3 justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2 items-center"><p className="font-semibold text-text-primary">{task.title}</p><span className={`status-badge ${priorityTone[task.priority]}`}>{task.priority}</span></div><p className="mt-1 text-sm text-text-secondary">{task.location} · Due {task.dueDate}</p><p className="mt-2 text-xs text-text-secondary">L{task.classification.level} · {task.classification.hierarchyLabel}</p></div><span className={`status-badge h-fit whitespace-nowrap ${statusTone[task.status]}`}>{task.status}</span></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-text-secondary">{task.assignedToSelf ? "Assigned to you" : `${labourer?.name ?? "Labourer pending"}`}</span><span className={task.dispatchStatus === "Not sent" ? "text-text-muted" : "text-status-ontrack"}>WhatsApp: {task.dispatchStatus}</span></div></button>; })}</div></section>
      <aside className="card p-5 h-fit xl:sticky xl:top-24">{selected ? <TaskInspector task={selected} onApprove={approve} onSelf={assignSelf} /> : <div className="py-12 text-center text-text-secondary"><p className="text-lg">Select a task</p><p className="mt-2 text-sm">Its AI classification and labour recommendation will appear here.</p></div>}</aside>
    </div>
  </div>;
}

function TaskInspector({ task, onApprove, onSelf }: { task: SupervisorTask; onApprove: (task: SupervisorTask, labourerId?: string) => void; onSelf: (task: SupervisorTask) => void }) {
  const [labourerId, setLabourerId] = useState(task.assignedLabourerId || task.suggestedLabourerId);
  const labourer = labourers.find(item => item.id === labourerId);
  return <div className="space-y-5"><div><p className="text-xs uppercase tracking-wide font-medium text-text-secondary">AI recommendation</p><h2 className="mt-1 text-lg font-semibold">{task.title}</h2><p className="mt-2 text-sm text-text-secondary">{task.description}</p></div><div className="p-4 bg-bg border border-border rounded-lg space-y-3"><div className="flex justify-between gap-4"><span className="text-sm text-text-secondary">Hierarchy</span><span className="text-sm font-medium text-right">L{task.classification.level}</span></div><p className="text-sm font-medium text-primary">{task.classification.hierarchyLabel}</p><p className="text-xs text-text-secondary">{task.classification.reasoning}</p><div className="pt-3 border-t flex justify-between"><span className="text-sm text-text-secondary">Confidence</span><span className="text-sm font-semibold text-status-ontrack">{task.classification.confidence}%</span></div></div><div><label className="text-sm font-medium">Recommended labourer</label><select value={labourerId} onChange={e => setLabourerId(e.target.value)} disabled={task.status !== "Awaiting Approval"} className="mt-2 w-full px-3 py-2 border border-border rounded-lg bg-surface-elevated text-sm disabled:opacity-70"><option value="">Select a labourer</option>{labourers.map(item => <option key={item.id} value={item.id}>{item.name} · {item.trade} · {item.availability}</option>)}</select>{labourer && <p className="mt-2 text-xs text-text-secondary">{labourer.trade} · {labourer.zone} · {labourer.activeTasks} active tasks · {labourer.phone}</p>}<p className="mt-2 text-xs text-text-secondary">{task.assignmentReason}</p></div>{task.status === "Awaiting Approval" ? <div className="space-y-2"><button onClick={() => onApprove(task, labourerId)} className="w-full px-4 py-2.5 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-light">Approve & send on WhatsApp</button><button onClick={() => onSelf(task)} className="w-full px-4 py-2.5 text-sm font-medium border border-border rounded-lg hover:bg-hover">Assign to myself</button></div> : <div className="p-3 rounded-lg bg-status-ontrack-bg text-status-ontrack text-sm">{task.assignedToSelf ? "You are managing this task." : `Assignment approved. WhatsApp status: ${task.dispatchStatus}.`}</div>}</div>;
}
